version: '3.8'
services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: 'gamelogdb'
      MARIADB_USER: 'gamelog'
      MARIADB_PASSWORD: 'gamelog'
      MARIADB_ROOT_PASSWORD: 'gamelog'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - maria-db:/var/lib/mysql
volumes:
  maria-db: