name: CI Unit Test

# Controls when the workflow will run
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'swagger/**'
      - '**/README.md'
      - '**/.gitignore'
    branches:
      - 'main'
    # This workflow executes every time a pull request is opened,
    # or if there are changes to the current pull request
    types:
      [synchronize,opened]
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_HOST: mysql
          MYSQL_DATABASE: gamelog
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17 + cache
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          # setup maven cache as well
          cache: maven
      - name: Unit-Test
        env:
          DB_HOST: localhost:3306
          DB_PASSWORD: ''
          DB_USER: root
          DB_NAME: gamelog
        run: mvn test -Psurefire
      - name: Upload Test Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/